// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace ListViewGroups
{
    [default_interface]
    runtimeclass ListViewPage : Microsoft.UI.Xaml.Controls.Page
    {
        ListViewPage();

        Windows.Foundation.Collections.IObservableVector<GroupSection> MyGroups{ get; };
        Microsoft.UI.Xaml.Data.CollectionViewSource MyCollectionViewSource;
    }

    [Windows.UI.Xaml.Data.Bindable]
    runtimeclass GroupSection
    {
        GroupSection();

        String Key{ get; };

        Windows.Foundation.Collections.IObservableVector<ListItem> MyItems{ get; };
    }

    runtimeclass ListItem
    {
        ListItem();

        String Name{ get; };
    }
}
